2024-06-10 11:44:54,047 INFO    StreamThr :2114 [internal.py:wandb_internal():85] W&B internal server running at pid: 2114, started at: 2024-06-10 11:44:54.046491
2024-06-10 11:44:54,048 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: status
2024-06-10 11:44:54,051 INFO    WriterThread:2114 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/run-nhx3j8f7.wandb
2024-06-10 11:44:54,052 DEBUG   SenderThread:2114 [sender.py:send():379] send: header
2024-06-10 11:44:54,081 DEBUG   SenderThread:2114 [sender.py:send():379] send: run
2024-06-10 11:44:54,768 INFO    SenderThread:2114 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files
2024-06-10 11:44:54,769 INFO    SenderThread:2114 [sender.py:_start_run_threads():1188] run started: nhx3j8f7 with start time 1718009094.047098
2024-06-10 11:44:54,776 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: check_version
2024-06-10 11:44:54,776 DEBUG   SenderThread:2114 [sender.py:send_request():406] send_request: check_version
2024-06-10 11:44:59,779 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:44:59,789 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: run_start
2024-06-10 11:44:59,797 DEBUG   HandlerThread:2114 [system_info.py:__init__():26] System info init
2024-06-10 11:44:59,797 DEBUG   HandlerThread:2114 [system_info.py:__init__():41] System info init done
2024-06-10 11:44:59,797 INFO    HandlerThread:2114 [system_monitor.py:start():194] Starting system monitor
2024-06-10 11:44:59,797 INFO    SystemMonitor:2114 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-10 11:44:59,797 INFO    HandlerThread:2114 [system_monitor.py:probe():214] Collecting system info
2024-06-10 11:44:59,797 INFO    SystemMonitor:2114 [interfaces.py:start():188] Started cpu monitoring
2024-06-10 11:44:59,800 INFO    SystemMonitor:2114 [interfaces.py:start():188] Started disk monitoring
2024-06-10 11:44:59,802 INFO    SystemMonitor:2114 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-10 11:44:59,804 INFO    SystemMonitor:2114 [interfaces.py:start():188] Started memory monitoring
2024-06-10 11:44:59,808 INFO    SystemMonitor:2114 [interfaces.py:start():188] Started network monitoring
2024-06-10 11:45:00,143 ERROR   HandlerThread:2114 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:00,145 DEBUG   HandlerThread:2114 [system_info.py:probe():152] Probing system
2024-06-10 11:45:00,149 DEBUG   HandlerThread:2114 [system_info.py:_probe_git():137] Probing git
2024-06-10 11:45:00,166 DEBUG   HandlerThread:2114 [system_info.py:_probe_git():145] Probing git done
2024-06-10 11:45:00,166 DEBUG   HandlerThread:2114 [system_info.py:probe():200] Probing system done
2024-06-10 11:45:00,166 DEBUG   HandlerThread:2114 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-10T08:45:00.145529', 'startedAt': '2024-06-10T08:44:54.022157', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '6f6027cea81ea0ccf2cf7dd032636796bc37170e'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-10 11:45:00,166 INFO    HandlerThread:2114 [system_monitor.py:probe():224] Finished collecting system info
2024-06-10 11:45:00,166 INFO    HandlerThread:2114 [system_monitor.py:probe():227] Publishing system info
2024-06-10 11:45:00,166 DEBUG   HandlerThread:2114 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-10 11:45:00,178 ERROR   HandlerThread:2114 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-10 11:45:00,178 DEBUG   HandlerThread:2114 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-10 11:45:00,179 INFO    HandlerThread:2114 [system_monitor.py:probe():229] Finished publishing system info
2024-06-10 11:45:00,185 DEBUG   SenderThread:2114 [sender.py:send():379] send: files
2024-06-10 11:45:00,186 INFO    SenderThread:2114 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-10 11:45:00,229 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:00,290 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: python_packages
2024-06-10 11:45:00,294 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:45:00,294 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:00,295 DEBUG   SenderThread:2114 [sender.py:send_request():406] send_request: python_packages
2024-06-10 11:45:00,303 DEBUG   SenderThread:2114 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:45:00,666 DEBUG   SenderThread:2114 [sender.py:send():379] send: telemetry
2024-06-10 11:45:00,790 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:00,790 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/wandb-metadata.json
2024-06-10 11:45:00,790 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/requirements.txt
2024-06-10 11:45:00,791 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/conda-environment.yaml
2024-06-10 11:45:01,150 INFO    wandb-upload_0:2114 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmpwfkmfnhwwandb/aszmmrn2-wandb-metadata.json
2024-06-10 11:45:01,296 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:02,301 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:02,367 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:02,798 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:03,303 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:04,308 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:04,495 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:04,805 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:04,993 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:45:05,313 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:06,315 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:06,634 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:06,812 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:07,319 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:08,321 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:08,786 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:08,818 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:09,326 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:10,033 DEBUG   HandlerThread:2114 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:45:10,825 INFO    Thread-12 :2114 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/files/output.log
2024-06-10 11:45:10,893 ERROR   gpuapple  :2114 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:11,121 WARNING StreamThr :2114 [internal.py:is_dead():413] Internal process exiting, parent pid 2071 disappeared
2024-06-10 11:45:11,122 ERROR   StreamThr :2114 [internal.py:wandb_internal():151] Internal process shutdown.
2024-06-10 11:45:11,166 INFO    HandlerThread:2114 [handler.py:finish():882] shutting down handler
2024-06-10 11:45:11,167 INFO    SenderThread:2114 [sender.py:finish():1608] shutting down sender
2024-06-10 11:45:11,167 INFO    WriterThread:2114 [datastore.py:close():296] close: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114454-nhx3j8f7/run-nhx3j8f7.wandb
2024-06-10 11:45:11,171 INFO    HandlerThread:2114 [system_monitor.py:finish():203] Stopping system monitor
2024-06-10 11:45:11,171 DEBUG   SystemMonitor:2114 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-10 11:45:11,171 DEBUG   SystemMonitor:2114 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-10 11:45:11,172 INFO    HandlerThread:2114 [interfaces.py:finish():200] Joined cpu monitor
2024-06-10 11:45:11,172 DEBUG   SystemMonitor:2114 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-10 11:45:11,172 INFO    HandlerThread:2114 [interfaces.py:finish():200] Joined disk monitor
2024-06-10 11:45:11,173 INFO    HandlerThread:2114 [interfaces.py:finish():200] Joined gpuapple monitor
2024-06-10 11:45:11,173 INFO    HandlerThread:2114 [interfaces.py:finish():200] Joined memory monitor
2024-06-10 11:45:11,173 INFO    HandlerThread:2114 [interfaces.py:finish():200] Joined network monitor
2024-06-10 11:45:11,831 INFO    MainThread:2114 [internal.py:handle_exit():75] Internal process exited
