2024-06-10 11:45:52,655 INFO    StreamThr :2240 [internal.py:wandb_internal():85] W&B internal server running at pid: 2240, started at: 2024-06-10 11:45:52.654066
2024-06-10 11:45:52,657 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status
2024-06-10 11:45:52,663 INFO    WriterThread:2240 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/run-6cm87741.wandb
2024-06-10 11:45:52,663 DEBUG   SenderThread:2240 [sender.py:send():379] send: header
2024-06-10 11:45:52,694 DEBUG   SenderThread:2240 [sender.py:send():379] send: run
2024-06-10 11:45:53,300 INFO    SenderThread:2240 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files
2024-06-10 11:45:53,300 INFO    SenderThread:2240 [sender.py:_start_run_threads():1188] run started: 6cm87741 with start time 1718009152.654513
2024-06-10 11:45:53,319 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: check_version
2024-06-10 11:45:53,319 DEBUG   SenderThread:2240 [sender.py:send_request():406] send_request: check_version
2024-06-10 11:45:53,564 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: run_start
2024-06-10 11:45:53,565 DEBUG   HandlerThread:2240 [system_info.py:__init__():26] System info init
2024-06-10 11:45:53,565 DEBUG   HandlerThread:2240 [system_info.py:__init__():41] System info init done
2024-06-10 11:45:53,565 INFO    HandlerThread:2240 [system_monitor.py:start():194] Starting system monitor
2024-06-10 11:45:53,565 INFO    SystemMonitor:2240 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-10 11:45:53,565 INFO    HandlerThread:2240 [system_monitor.py:probe():214] Collecting system info
2024-06-10 11:45:53,566 INFO    SystemMonitor:2240 [interfaces.py:start():188] Started cpu monitoring
2024-06-10 11:45:53,569 INFO    SystemMonitor:2240 [interfaces.py:start():188] Started disk monitoring
2024-06-10 11:45:53,571 INFO    SystemMonitor:2240 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-10 11:45:53,572 INFO    SystemMonitor:2240 [interfaces.py:start():188] Started memory monitoring
2024-06-10 11:45:53,572 INFO    SystemMonitor:2240 [interfaces.py:start():188] Started network monitoring
2024-06-10 11:45:53,684 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:53,774 ERROR   HandlerThread:2240 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:53,775 DEBUG   HandlerThread:2240 [system_info.py:probe():152] Probing system
2024-06-10 11:45:53,778 DEBUG   HandlerThread:2240 [system_info.py:_probe_git():137] Probing git
2024-06-10 11:45:53,792 DEBUG   HandlerThread:2240 [system_info.py:_probe_git():145] Probing git done
2024-06-10 11:45:53,793 DEBUG   HandlerThread:2240 [system_info.py:probe():200] Probing system done
2024-06-10 11:45:53,793 DEBUG   HandlerThread:2240 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-10T08:45:53.775105', 'startedAt': '2024-06-10T08:45:52.650058', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '6f6027cea81ea0ccf2cf7dd032636796bc37170e'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-10 11:45:53,793 INFO    HandlerThread:2240 [system_monitor.py:probe():224] Finished collecting system info
2024-06-10 11:45:53,793 INFO    HandlerThread:2240 [system_monitor.py:probe():227] Publishing system info
2024-06-10 11:45:53,793 DEBUG   HandlerThread:2240 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-10 11:45:53,802 ERROR   HandlerThread:2240 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-10 11:45:53,802 DEBUG   HandlerThread:2240 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-10 11:45:53,805 INFO    HandlerThread:2240 [system_monitor.py:probe():229] Finished publishing system info
2024-06-10 11:45:53,809 DEBUG   SenderThread:2240 [sender.py:send():379] send: files
2024-06-10 11:45:53,809 INFO    SenderThread:2240 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-10 11:45:53,901 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: python_packages
2024-06-10 11:45:53,917 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:45:53,917 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:53,917 DEBUG   SenderThread:2240 [sender.py:send_request():406] send_request: python_packages
2024-06-10 11:45:53,918 DEBUG   SenderThread:2240 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:45:54,306 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/requirements.txt
2024-06-10 11:45:54,306 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/wandb-metadata.json
2024-06-10 11:45:54,306 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/conda-environment.yaml
2024-06-10 11:45:54,344 DEBUG   SenderThread:2240 [sender.py:send():379] send: telemetry
2024-06-10 11:45:54,671 INFO    wandb-upload_0:2240 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmphleucw3mwandb/as1gekha-wandb-metadata.json
2024-06-10 11:45:54,903 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:55,310 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:45:55,840 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:55,908 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:56,913 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:57,319 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:45:57,726 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:45:57,917 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:57,972 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:45:58,919 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:45:59,325 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:45:59,924 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:00,116 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:00,928 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:01,333 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:01,930 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:02,245 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:02,896 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:46:02,935 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:03,342 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:03,940 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:04,387 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:04,942 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:05,352 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:05,946 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:06,522 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:06,951 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:07,359 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:07,956 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:08,018 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:46:08,688 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:08,906 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:46:08,907 DEBUG   SenderThread:2240 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:46:08,957 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:09,366 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:09,957 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:10,866 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:10,958 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:11,376 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:11,960 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:12,966 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:13,011 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:13,024 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:46:13,384 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:13,969 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:14,969 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:15,171 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:15,393 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:15,974 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:16,980 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:17,345 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:17,402 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:17,983 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:18,152 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:46:18,988 DEBUG   HandlerThread:2240 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:46:19,410 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:19,449 ERROR   gpuapple  :2240 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:46:19,613 INFO    cpu       :2240 [interfaces.py:monitor():138] Process cpu has exited.
2024-06-10 11:46:19,614 DEBUG   SystemMonitor:2240 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-10 11:46:19,614 DEBUG   SystemMonitor:2240 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-10 11:46:19,614 DEBUG   SystemMonitor:2240 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-10 11:46:19,614 DEBUG   SenderThread:2240 [sender.py:send():379] send: telemetry
2024-06-10 11:46:19,614 DEBUG   SenderThread:2240 [sender.py:send():379] send: stats
2024-06-10 11:46:21,419 INFO    Thread-12 :2240 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_114552-6cm87741/files/output.log
2024-06-10 11:46:21,681 INFO    MainThread:2240 [internal.py:handle_exit():75] Internal process exited
