2024-06-10 13:03:00,648 INFO    StreamThr :3445 [internal.py:wandb_internal():85] W&B internal server running at pid: 3445, started at: 2024-06-10 13:03:00.646503
2024-06-10 13:03:00,650 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status
2024-06-10 13:03:00,656 INFO    WriterThread:3445 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/run-4df1kmv9.wandb
2024-06-10 13:03:00,657 DEBUG   SenderThread:3445 [sender.py:send():379] send: header
2024-06-10 13:03:00,697 DEBUG   SenderThread:3445 [sender.py:send():379] send: run
2024-06-10 13:03:01,296 INFO    SenderThread:3445 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files
2024-06-10 13:03:01,297 INFO    SenderThread:3445 [sender.py:_start_run_threads():1188] run started: 4df1kmv9 with start time 1718013780.647716
2024-06-10 13:03:01,308 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: check_version
2024-06-10 13:03:01,308 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: check_version
2024-06-10 13:03:01,685 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: run_start
2024-06-10 13:03:01,686 DEBUG   HandlerThread:3445 [system_info.py:__init__():26] System info init
2024-06-10 13:03:01,686 DEBUG   HandlerThread:3445 [system_info.py:__init__():41] System info init done
2024-06-10 13:03:01,686 INFO    HandlerThread:3445 [system_monitor.py:start():194] Starting system monitor
2024-06-10 13:03:01,686 INFO    SystemMonitor:3445 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-10 13:03:01,686 INFO    HandlerThread:3445 [system_monitor.py:probe():214] Collecting system info
2024-06-10 13:03:01,686 INFO    SystemMonitor:3445 [interfaces.py:start():188] Started cpu monitoring
2024-06-10 13:03:01,687 INFO    SystemMonitor:3445 [interfaces.py:start():188] Started disk monitoring
2024-06-10 13:03:01,688 INFO    SystemMonitor:3445 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-10 13:03:01,690 INFO    SystemMonitor:3445 [interfaces.py:start():188] Started memory monitoring
2024-06-10 13:03:01,692 INFO    SystemMonitor:3445 [interfaces.py:start():188] Started network monitoring
2024-06-10 13:03:01,897 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:01,971 ERROR   HandlerThread:3445 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:01,971 DEBUG   HandlerThread:3445 [system_info.py:probe():152] Probing system
2024-06-10 13:03:01,974 DEBUG   HandlerThread:3445 [system_info.py:_probe_git():137] Probing git
2024-06-10 13:03:01,988 DEBUG   HandlerThread:3445 [system_info.py:_probe_git():145] Probing git done
2024-06-10 13:03:01,988 DEBUG   HandlerThread:3445 [system_info.py:probe():200] Probing system done
2024-06-10 13:03:01,988 DEBUG   HandlerThread:3445 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-10T10:03:01.971813', 'startedAt': '2024-06-10T10:03:00.631295', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '80cc1b3a0aaf87fd0f522e86c3be646c767e6aac'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-10 13:03:01,988 INFO    HandlerThread:3445 [system_monitor.py:probe():224] Finished collecting system info
2024-06-10 13:03:01,988 INFO    HandlerThread:3445 [system_monitor.py:probe():227] Publishing system info
2024-06-10 13:03:01,988 DEBUG   HandlerThread:3445 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-10 13:03:01,992 ERROR   HandlerThread:3445 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-10 13:03:01,993 DEBUG   HandlerThread:3445 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-10 13:03:01,993 INFO    HandlerThread:3445 [system_monitor.py:probe():229] Finished publishing system info
2024-06-10 13:03:01,997 DEBUG   SenderThread:3445 [sender.py:send():379] send: files
2024-06-10 13:03:01,997 INFO    SenderThread:3445 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-10 13:03:02,079 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: python_packages
2024-06-10 13:03:02,080 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: python_packages
2024-06-10 13:03:02,080 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 13:03:02,080 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: stop_status
2024-06-10 13:03:02,081 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:02,298 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/requirements.txt
2024-06-10 13:03:02,299 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/wandb-metadata.json
2024-06-10 13:03:02,299 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/conda-environment.yaml
2024-06-10 13:03:02,443 DEBUG   SenderThread:3445 [sender.py:send():379] send: telemetry
2024-06-10 13:03:02,935 INFO    wandb-upload_0:3445 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmpex9weafewandb/iciqdjsw-wandb-metadata.json
2024-06-10 13:03:03,081 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:03,302 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:04,042 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:04,086 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:05,089 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:05,313 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:05,763 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:06,094 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:06,183 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:07,098 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:07,323 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:08,103 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:08,342 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:09,106 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:09,331 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:10,107 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:10,468 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:11,007 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:11,108 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:11,341 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:12,110 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:12,624 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:13,115 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:13,348 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:14,120 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:14,746 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:15,125 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:15,355 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:16,130 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:16,316 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:16,873 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:17,085 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 13:03:17,085 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: stop_status
2024-06-10 13:03:17,132 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:17,364 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:18,134 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:19,012 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:19,139 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:19,373 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:20,144 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:21,145 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:21,301 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:21,384 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:21,458 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:22,150 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:23,155 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:23,394 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:23,399 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:24,158 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:25,163 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:25,406 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:25,500 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:26,168 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:26,530 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:27,173 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:27,413 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:27,621 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:28,178 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:29,183 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:29,423 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:29,761 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:30,188 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:31,193 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:31,430 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:31,855 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:31,884 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:32,091 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 13:03:32,091 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: stop_status
2024-06-10 13:03:32,198 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:32,436 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/config.yaml
2024-06-10 13:03:33,203 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:33,441 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:33,977 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:34,205 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:35,209 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:35,448 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:36,092 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:36,214 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:37,113 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:37,219 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:37,458 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:38,222 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:38,224 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:39,227 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:39,469 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:40,231 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:40,333 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:41,232 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:41,480 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:42,115 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:42,237 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:42,436 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:43,241 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:43,487 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:44,246 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:44,536 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:45,251 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:45,498 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:46,254 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:46,685 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:47,095 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 13:03:47,095 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: stop_status
2024-06-10 13:03:47,256 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:47,349 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:47,506 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:48,261 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:48,812 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:49,266 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:49,515 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:50,269 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:50,914 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:51,274 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:51,525 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:52,277 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:52,419 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:53,028 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:53,282 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:53,536 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:54,284 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:55,124 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:55,284 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:55,546 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:56,289 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:57,251 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:57,290 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:57,555 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:03:57,701 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:03:58,292 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:59,295 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:03:59,390 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:03:59,565 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:00,297 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:01,298 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:01,502 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:01,576 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:01,696 DEBUG   SystemMonitor:3445 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-10 13:04:01,697 DEBUG   SenderThread:3445 [sender.py:send():379] send: telemetry
2024-06-10 13:04:01,697 DEBUG   SenderThread:3445 [sender.py:send():379] send: stats
2024-06-10 13:04:02,100 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 13:04:02,100 DEBUG   SenderThread:3445 [sender.py:send_request():406] send_request: stop_status
2024-06-10 13:04:02,303 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:03,050 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:04:03,304 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:03,583 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:03,584 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/config.yaml
2024-06-10 13:04:03,606 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:04,306 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:05,311 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:05,593 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:05,718 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:06,316 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:07,321 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:07,604 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:07,840 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:08,326 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:08,948 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:04:09,328 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:09,610 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:09,965 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:10,332 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:11,337 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:11,621 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:12,074 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:12,342 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:13,347 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:13,629 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:14,177 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:14,226 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 13:04:14,351 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:15,354 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:15,640 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:16,324 ERROR   gpuapple  :3445 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 13:04:16,356 DEBUG   HandlerThread:3445 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 13:04:17,650 INFO    Thread-12 :3445 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_130300-4df1kmv9/files/output.log
2024-06-10 13:04:17,850 INFO    memory    :3445 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2024-06-10 13:04:17,851 DEBUG   SystemMonitor:3445 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-10 13:04:17,852 DEBUG   SystemMonitor:3445 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-10 13:04:17,854 DEBUG   SenderThread:3445 [sender.py:send():379] send: stats
2024-06-10 13:04:17,999 INFO    MainThread:3445 [internal.py:handle_exit():75] Internal process exited
