2024-06-10 11:25:23,412 INFO    StreamThr :721 [internal.py:wandb_internal():85] W&B internal server running at pid: 721, started at: 2024-06-10 11:25:23.411167
2024-06-10 11:25:23,414 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status
2024-06-10 11:25:23,415 INFO    WriterThread:721 [datastore.py:open_for_write():87] open: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/run-b4ed4top.wandb
2024-06-10 11:25:23,417 DEBUG   SenderThread:721 [sender.py:send():379] send: header
2024-06-10 11:25:23,445 DEBUG   SenderThread:721 [sender.py:send():379] send: run
2024-06-10 11:25:24,118 INFO    SenderThread:721 [dir_watcher.py:__init__():211] watching files in: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files
2024-06-10 11:25:24,118 INFO    SenderThread:721 [sender.py:_start_run_threads():1188] run started: b4ed4top with start time 1718007923.411895
2024-06-10 11:25:24,128 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: check_version
2024-06-10 11:25:24,128 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: check_version
2024-06-10 11:25:24,459 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: run_start
2024-06-10 11:25:24,462 DEBUG   HandlerThread:721 [system_info.py:__init__():26] System info init
2024-06-10 11:25:24,462 DEBUG   HandlerThread:721 [system_info.py:__init__():41] System info init done
2024-06-10 11:25:24,462 INFO    HandlerThread:721 [system_monitor.py:start():194] Starting system monitor
2024-06-10 11:25:24,462 INFO    SystemMonitor:721 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-10 11:25:24,462 INFO    HandlerThread:721 [system_monitor.py:probe():214] Collecting system info
2024-06-10 11:25:24,464 INFO    SystemMonitor:721 [interfaces.py:start():188] Started cpu monitoring
2024-06-10 11:25:24,465 INFO    SystemMonitor:721 [interfaces.py:start():188] Started disk monitoring
2024-06-10 11:25:24,471 INFO    SystemMonitor:721 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-10 11:25:24,474 INFO    SystemMonitor:721 [interfaces.py:start():188] Started memory monitoring
2024-06-10 11:25:24,475 INFO    SystemMonitor:721 [interfaces.py:start():188] Started network monitoring
2024-06-10 11:25:25,365 ERROR   HandlerThread:721 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:25,367 DEBUG   HandlerThread:721 [system_info.py:probe():152] Probing system
2024-06-10 11:25:25,370 DEBUG   HandlerThread:721 [system_info.py:_probe_git():137] Probing git
2024-06-10 11:25:25,383 DEBUG   HandlerThread:721 [system_info.py:_probe_git():145] Probing git done
2024-06-10 11:25:25,383 DEBUG   HandlerThread:721 [system_info.py:probe():200] Probing system done
2024-06-10 11:25:25,383 DEBUG   HandlerThread:721 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.8.18', 'heartbeatAt': '2024-06-10T08:25:25.367078', 'startedAt': '2024-06-10T08:25:23.403029', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/two_d_train.py', 'codePathLocal': 'two_d_train.py', 'codePath': 'two_d_train.py', 'git': {'remote': 'https://github.com/idanv87/deep_attention.git', 'commit': '6f6027cea81ea0ccf2cf7dd032636796bc37170e'}, 'email': 'idanv@campus.technion.ac.il', 'root': '/Users/idanversano/Documents/project_geo_deeponet/deep_attention/src', 'host': 'idans-MacBook-Air.local', 'username': 'idanversano', 'executable': '/Users/idanversano/miniforge3/envs/torch_env/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 9.562911987304688}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-10 11:25:25,383 INFO    HandlerThread:721 [system_monitor.py:probe():224] Finished collecting system info
2024-06-10 11:25:25,383 INFO    HandlerThread:721 [system_monitor.py:probe():227] Publishing system info
2024-06-10 11:25:25,383 DEBUG   HandlerThread:721 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-06-10 11:25:25,386 ERROR   HandlerThread:721 [system_info.py:_save_conda():223] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/system_info.py", line 216, in _save_conda
    subprocess.call(
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 1720, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2024-06-10 11:25:25,386 DEBUG   HandlerThread:721 [system_info.py:_save_conda():224] Saving conda packages done
2024-06-10 11:25:25,387 INFO    HandlerThread:721 [system_monitor.py:probe():229] Finished publishing system info
2024-06-10 11:25:25,391 DEBUG   SenderThread:721 [sender.py:send():379] send: files
2024-06-10 11:25:25,391 INFO    SenderThread:721 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-06-10 11:25:25,454 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:25,477 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: python_packages
2024-06-10 11:25:25,477 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:25:25,477 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: python_packages
2024-06-10 11:25:25,477 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:25,478 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:25:25,863 DEBUG   SenderThread:721 [sender.py:send():379] send: telemetry
2024-06-10 11:25:26,128 INFO    Thread-12 :721 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/conda-environment.yaml
2024-06-10 11:25:26,129 INFO    Thread-12 :721 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:26,129 INFO    Thread-12 :721 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/requirements.txt
2024-06-10 11:25:26,129 INFO    Thread-12 :721 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/wandb-metadata.json
2024-06-10 11:25:26,481 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:26,534 INFO    wandb-upload_0:721 [upload_job.py:push():130] Uploaded file /var/folders/tf/xl2_rn496w36wzs_pk18q7vr0000gn/T/tmpjtyxv2vjwandb/1ktbhqy0-wandb-metadata.json
2024-06-10 11:25:27,486 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:27,568 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:28,139 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:28,481 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:28,488 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:29,493 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:29,682 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:30,149 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:30,498 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:31,499 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:31,791 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:32,160 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:32,505 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:33,506 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:33,564 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:33,895 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:34,166 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:34,512 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:35,517 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:36,007 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:36,177 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:36,517 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:37,522 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:38,114 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:38,187 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:38,522 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:38,634 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:39,528 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:40,195 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:40,223 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:40,482 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:25:40,483 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:25:40,533 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:41,538 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:42,205 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:42,334 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:42,540 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:43,540 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:43,732 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:44,216 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:44,446 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:44,543 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:45,542 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:46,225 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:46,548 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:46,555 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:47,550 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:48,235 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:48,555 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:48,665 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:48,813 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:49,560 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:50,246 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:50,564 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:50,779 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:51,691 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:51,920 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: partial_history
2024-06-10 11:25:51,921 DEBUG   SenderThread:721 [sender.py:send():379] send: history
2024-06-10 11:25:51,921 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: summary_record
2024-06-10 11:25:51,921 INFO    SenderThread:721 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-10 11:25:52,256 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:52,257 INFO    Thread-12 :721 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/wandb-summary.json
2024-06-10 11:25:52,669 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:52,912 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:53,672 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:53,910 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:54,266 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:54,266 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/config.yaml
2024-06-10 11:25:54,677 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:55,031 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:55,487 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:25:55,488 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:25:55,682 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:56,268 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:56,687 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:57,153 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:57,688 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:58,275 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:25:58,690 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:25:59,165 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:25:59,268 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:25:59,692 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:00,285 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:00,696 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:01,391 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:01,701 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:02,296 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:02,703 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:03,509 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:03,708 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:04,241 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:04,304 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:04,713 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:05,667 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:05,714 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:06,312 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:06,716 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:07,721 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:07,791 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:08,322 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:08,723 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:09,307 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:09,728 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:09,924 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:10,333 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:10,493 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:26:10,493 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:26:10,730 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:11,733 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:12,043 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:12,343 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:12,738 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:13,739 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:14,191 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:14,349 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:14,349 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:14,744 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:15,749 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:16,312 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:16,360 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:16,755 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:17,758 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:18,371 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:18,431 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:18,760 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:19,432 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:19,760 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:20,166 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: partial_history
2024-06-10 11:26:20,166 DEBUG   SenderThread:721 [sender.py:send():379] send: history
2024-06-10 11:26:20,167 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: summary_record
2024-06-10 11:26:20,167 INFO    SenderThread:721 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-10 11:26:20,381 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/wandb-summary.json
2024-06-10 11:26:20,382 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:20,558 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:20,764 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:21,766 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:22,393 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:22,690 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:22,768 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:23,773 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:24,404 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:24,454 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:24,482 DEBUG   SystemMonitor:721 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-10 11:26:24,483 DEBUG   SenderThread:721 [sender.py:send():379] send: telemetry
2024-06-10 11:26:24,483 DEBUG   SenderThread:721 [sender.py:send():379] send: stats
2024-06-10 11:26:24,779 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:24,811 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:25,498 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:26:25,499 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:26:25,783 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:26,414 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:26,788 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:26,933 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:27,793 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:28,425 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:28,795 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:29,175 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:29,568 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:29,798 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:30,436 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:30,802 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:31,300 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:31,807 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:32,445 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:32,812 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:33,426 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:33,817 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:34,454 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:34,591 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:34,819 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:35,552 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:35,824 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:36,465 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:36,828 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:37,672 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:37,833 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:38,476 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:38,835 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:39,629 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:39,795 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:39,840 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:40,486 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:40,504 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:26:40,504 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:26:40,845 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:41,849 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:41,984 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:42,498 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:42,852 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:43,853 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:44,116 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:44,508 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:44,630 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:44,853 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:45,855 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:46,379 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:46,516 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:46,860 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:47,445 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: partial_history
2024-06-10 11:26:47,446 DEBUG   SenderThread:721 [sender.py:send():379] send: history
2024-06-10 11:26:47,446 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: summary_record
2024-06-10 11:26:47,447 INFO    SenderThread:721 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-10 11:26:47,521 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/wandb-summary.json
2024-06-10 11:26:47,864 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:48,510 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:48,527 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:48,869 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:49,748 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:49,874 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:50,530 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:50,706 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:50,878 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:51,883 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:52,538 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:52,888 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:52,967 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:53,890 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:54,490 DEBUG   SenderThread:721 [sender.py:send():379] send: stats
2024-06-10 11:26:54,545 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:54,829 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:26:54,894 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:55,132 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:55,508 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:26:55,508 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:26:55,550 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/config.yaml
2024-06-10 11:26:55,899 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:56,555 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:56,905 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:57,315 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:57,910 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:58,566 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:26:58,912 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:26:59,454 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:26:59,914 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:00,070 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:00,575 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:00,919 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:01,613 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:01,923 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:02,585 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:02,927 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:03,744 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:03,933 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:04,594 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:04,937 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:05,133 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:05,878 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:05,940 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:06,605 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:06,945 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:07,947 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:08,013 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:08,615 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:08,949 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:09,954 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:10,171 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:10,228 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:10,513 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:27:10,516 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:27:10,626 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:10,959 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:11,960 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:12,323 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:12,637 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:12,963 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:13,965 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:14,466 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:14,648 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:14,970 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:15,244 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:15,975 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:16,602 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:16,654 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:16,825 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: partial_history
2024-06-10 11:27:16,826 DEBUG   SenderThread:721 [sender.py:send():379] send: history
2024-06-10 11:27:16,826 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: summary_record
2024-06-10 11:27:16,826 INFO    SenderThread:721 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-06-10 11:27:16,977 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:17,659 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/wandb-summary.json
2024-06-10 11:27:17,981 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:18,665 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:18,735 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:18,983 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:19,988 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:20,275 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:20,674 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:20,871 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:20,993 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:21,996 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:22,684 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:23,001 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:23,007 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:24,007 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:24,496 DEBUG   SenderThread:721 [sender.py:send():379] send: stats
2024-06-10 11:27:24,695 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:25,008 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:25,142 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:25,391 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:25,519 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: stop_status
2024-06-10 11:27:25,519 DEBUG   SenderThread:721 [sender.py:send_request():406] send_request: stop_status
2024-06-10 11:27:26,013 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:26,706 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:27,018 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:27,273 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:28,023 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:28,715 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:29,025 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:29,443 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:30,030 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:30,477 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:30,722 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:31,037 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:31,585 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:32,039 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:32,730 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:33,041 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:33,726 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:34,046 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:34,739 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:35,049 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:35,499 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: status_report
2024-06-10 11:27:35,861 ERROR   gpuapple  :721 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/idanversano/miniforge3/envs/torch_env/lib/python3.8/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-10 11:27:36,054 DEBUG   HandlerThread:721 [handler.py:handle_request():158] handle_request: internal_messages
2024-06-10 11:27:36,751 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:36,763 INFO    cpu       :721 [interfaces.py:monitor():138] Process cpu has exited.
2024-06-10 11:27:36,763 DEBUG   SystemMonitor:721 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-06-10 11:27:36,764 DEBUG   SystemMonitor:721 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-06-10 11:27:36,765 DEBUG   SenderThread:721 [sender.py:send():379] send: stats
2024-06-10 11:27:38,761 INFO    Thread-12 :721 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/idanversano/Documents/project_geo_deeponet/deep_attention/src/wandb/run-20240610_112523-b4ed4top/files/output.log
2024-06-10 11:27:39,032 INFO    MainThread:721 [internal.py:handle_exit():75] Internal process exited
